package panel.creator;

import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 * Controls panel controls all the variables that the user can change
 *
 * @author EricGummerson
 */
public final class ControlsPanel extends javax.swing.JPanel {

    public MainFrame mf;
    public Store store;    
    public int numRacks;
    public int numFans;
    public int numSG;
    public int numComp;
    public int numSystems;
    

    /**
     * Creates new form MainPanel
     *
     * @param mf
     * @param store
     */
    public ControlsPanel(MainFrame mf, Store store) {
        this.mf = mf;
        initComponents();
        this.store = store;
    }
    
    /**
     * Gets the file names for the displays
     * Format: StoreName Tab WidthxHeight.png 
     * @param filePath  path of the folder to save in
     * @param d         dimension size of the panel
     * @return array of strings, file names used to save all the files
     */
    public String[] getFileNames(String filePath, Dimension d){
        String [] fn = new String[numRacks+2];
        String storeName = store.getStoreName();
        
        fn[0] = filePath + storeName + " [1] Main - " + + d.width + "x" + d.height + ".png";
        
        for(int i = 1; i <= numRacks; i++){
            fn[i] = filePath + storeName + " ["+(i+1)+"] Rack{" + store.getRackName(i-1)
                             + "} - " + d.width + "x" + d.height + ".png";
        }
        fn[fn.length-1] = filePath + storeName + " ["+(fn.length)+"] Loads - " + + d.width + "x" + d.height + ".png";
        
        return fn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _Panel_Controls = new javax.swing.JPanel();
        _Label_Site = new javax.swing.JLabel();
        _TextField_SiteName = new javax.swing.JTextField();
        _Label_NumberRacks = new javax.swing.JLabel();
        _ComboBox_Racks = new javax.swing.JComboBox();
        _Label_RackSelected = new javax.swing.JLabel();
        _Label_CondenserFans = new javax.swing.JLabel();
        _Label_NumberSuctionGroups = new javax.swing.JLabel();
        _Label_SGSelected = new javax.swing.JLabel();
        _Label_SuctionGroupOptions = new javax.swing.JLabel();
        _ComboBox_SuctionGroups = new javax.swing.JComboBox();
        _Label_Compressors = new javax.swing.JLabel();
        _Label_NumberSystems = new javax.swing.JLabel();
        _Label_SuctionGroupName = new javax.swing.JLabel();
        _TextField_SuctionGroupName = new javax.swing.JTextField();
        _FormattedTF_NumRacks = new javax.swing.JFormattedTextField();
        _Label_Title = new javax.swing.JLabel();
        _FormattedTF_NumFans = new javax.swing.JFormattedTextField();
        _FormattedTF_NumSG = new javax.swing.JFormattedTextField();
        _FormattedTF_NumComp = new javax.swing.JFormattedTextField();
        _FormattedTF_NumSystems = new javax.swing.JFormattedTextField();
        _Panel_NamePanel = new javax.swing.JPanel();
        _ComboBox_RackNumber = new javax.swing.JComboBox();
        _Label_RackNumber = new javax.swing.JLabel();
        _Label_RackName = new javax.swing.JLabel();
        _TextField_RackName = new javax.swing.JTextField();
        _Button_RackPrev = new javax.swing.JButton();
        _Button_RackNext = new javax.swing.JButton();
        _Label_CompressorNumber = new javax.swing.JLabel();
        _ComboBox_CompressorNumber = new javax.swing.JComboBox();
        _Label_CompressorName = new javax.swing.JLabel();
        _TextField_CompressorName = new javax.swing.JTextField();
        _Button_CompPrev = new javax.swing.JButton();
        _Button_CompNext = new javax.swing.JButton();
        _Label_SystemNumber = new javax.swing.JLabel();
        _TextField_SystemName = new javax.swing.JTextField();
        _Button_SysNext = new javax.swing.JButton();
        _Button_SysPrev = new javax.swing.JButton();
        _ComboBox_Systems = new javax.swing.JComboBox();
        _Label_SystemName = new javax.swing.JLabel();
        _Label_SystemSave = new javax.swing.JLabel();
        _Label_StoreLogo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(969, 629));

        _Label_Site.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _Label_Site.setText("Name of Site");

        _TextField_SiteName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _TextField_SiteName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _TextField_SiteName.setText("Site Name");
        _TextField_SiteName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _TextField_SiteNameFocusLost(evt);
            }
        });

        _Label_NumberRacks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _Label_NumberRacks.setText("Number of Racks");

        _ComboBox_Racks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _ComboBox_Racks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rack 1" }));
        _ComboBox_Racks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ComboBox_RacksActionPerformed(evt);
            }
        });

        _Label_RackSelected.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        _Label_RackSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_RackSelected.setText("Rack 1 Options");

        _Label_CondenserFans.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_CondenserFans.setText("Number of Condenser Fans");

        _Label_NumberSuctionGroups.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_NumberSuctionGroups.setText("Number of Suction Groups");

        _Label_SGSelected.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        _Label_SGSelected.setText("Suction Group 1 Options");

        _Label_SuctionGroupOptions.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_SuctionGroupOptions.setText("Suction Group Options");

        _ComboBox_SuctionGroups.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _ComboBox_SuctionGroups.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suction Group 1" }));
        _ComboBox_SuctionGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ComboBox_SuctionGroupsActionPerformed(evt);
            }
        });

        _Label_Compressors.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_Compressors.setText("Number of Compressors");

        _Label_NumberSystems.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_NumberSystems.setText("Number of Systems");

        _Label_SuctionGroupName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_SuctionGroupName.setText("Suction Group Name");

        _TextField_SuctionGroupName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _TextField_SuctionGroupName.setText("Suction Group 1");
        _TextField_SuctionGroupName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _TextField_SuctionGroupNameFocusLost(evt);
            }
        });

        _FormattedTF_NumRacks.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_NumRacks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_NumRacks.setText("1");
        _FormattedTF_NumRacks.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                _FormattedTF_NumRacksPropertyChange(evt);
            }
        });

        _Label_Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _Label_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_Title.setText("Background Creator Settings");

        _FormattedTF_NumFans.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_NumFans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_NumFans.setText("5");
        _FormattedTF_NumFans.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                _FormattedTF_NumFansPropertyChange(evt);
            }
        });

        _FormattedTF_NumSG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_NumSG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_NumSG.setText("1");
        _FormattedTF_NumSG.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                _FormattedTF_NumSGPropertyChange(evt);
            }
        });

        _FormattedTF_NumComp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_NumComp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_NumComp.setText("5");
        _FormattedTF_NumComp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                _FormattedTF_NumCompPropertyChange(evt);
            }
        });

        _FormattedTF_NumSystems.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_NumSystems.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_NumSystems.setText("5");
        _FormattedTF_NumSystems.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                _FormattedTF_NumSystemsPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout _Panel_ControlsLayout = new javax.swing.GroupLayout(_Panel_Controls);
        _Panel_Controls.setLayout(_Panel_ControlsLayout);
        _Panel_ControlsLayout.setHorizontalGroup(
            _Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _Panel_ControlsLayout.createSequentialGroup()
                        .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addComponent(_Label_NumberRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(_FormattedTF_NumRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(_Label_Site, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(_TextField_SiteName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(_ComboBox_Racks, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))
                    .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                        .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addComponent(_Label_Compressors, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_FormattedTF_NumComp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(_Label_NumberSystems, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_FormattedTF_NumSystems, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(_Label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(_Label_RackSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addComponent(_Label_CondenserFans, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_FormattedTF_NumFans, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(_Label_NumberSuctionGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                .addComponent(_Label_SuctionGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_Label_SGSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(_TextField_SuctionGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(_FormattedTF_NumSG, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                                    .addComponent(_Label_SuctionGroupOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(_ComboBox_SuctionGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        _Panel_ControlsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_FormattedTF_NumComp, _FormattedTF_NumFans, _FormattedTF_NumRacks, _FormattedTF_NumSG, _FormattedTF_NumSystems});

        _Panel_ControlsLayout.setVerticalGroup(
            _Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_Panel_ControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_Label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_TextField_SiteName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Label_Site, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Label_NumberRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_FormattedTF_NumRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_ComboBox_Racks, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(_Label_RackSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_Label_CondenserFans, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_FormattedTF_NumFans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_FormattedTF_NumSG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Label_NumberSuctionGroups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Label_SuctionGroupOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_ComboBox_SuctionGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Label_SuctionGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_TextField_SuctionGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_Label_SGSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Label_Compressors, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_FormattedTF_NumComp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Label_NumberSystems, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_FormattedTF_NumSystems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        _Panel_ControlsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {_FormattedTF_NumComp, _FormattedTF_NumFans, _FormattedTF_NumRacks, _FormattedTF_NumSG, _FormattedTF_NumSystems});

        _ComboBox_RackNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rack 1" }));
        _ComboBox_RackNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ComboBox_RackNumberActionPerformed(evt);
            }
        });

        _Label_RackNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _Label_RackNumber.setText("Rack Number      ");
        _Label_RackNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        _Label_RackName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _Label_RackName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_RackName.setText("Rack Name");

        _TextField_RackName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _TextField_RackName.setText("Rack 1");

        _Button_RackPrev.setText("Previous");
        _Button_RackPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_RackPrevActionPerformed(evt);
            }
        });

        _Button_RackNext.setText("Next");
        _Button_RackNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_RackNextActionPerformed(evt);
            }
        });

        _Label_CompressorNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _Label_CompressorNumber.setText("Compressor Number");
        _Label_CompressorNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        _ComboBox_CompressorNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compressor 1" }));
        _ComboBox_CompressorNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ComboBox_CompressorNumberActionPerformed(evt);
            }
        });

        _Label_CompressorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _Label_CompressorName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_CompressorName.setText("Compressor Name");

        _TextField_CompressorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _TextField_CompressorName.setText("Compressor 1");

        _Button_CompPrev.setText("Previous");
        _Button_CompPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_CompPrevActionPerformed(evt);
            }
        });

        _Button_CompNext.setText("Next");
        _Button_CompNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_CompNextActionPerformed(evt);
            }
        });

        _Label_SystemNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _Label_SystemNumber.setText("System Number");
        _Label_SystemNumber.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        _TextField_SystemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _TextField_SystemName.setText("System 1");

        _Button_SysNext.setText("Next");
        _Button_SysNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_SysNextActionPerformed(evt);
            }
        });

        _Button_SysPrev.setText("Previous");
        _Button_SysPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_SysPrevActionPerformed(evt);
            }
        });

        _ComboBox_Systems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "System 1" }));
        _ComboBox_Systems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ComboBox_SystemsActionPerformed(evt);
            }
        });

        _Label_SystemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _Label_SystemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_SystemName.setText("System Name");

        _Label_SystemSave.setForeground(new java.awt.Color(255, 0, 0));
        _Label_SystemSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_SystemSave.setText("These options save the name");

        javax.swing.GroupLayout _Panel_NamePanelLayout = new javax.swing.GroupLayout(_Panel_NamePanel);
        _Panel_NamePanel.setLayout(_Panel_NamePanelLayout);
        _Panel_NamePanelLayout.setHorizontalGroup(
            _Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                        .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_Label_SystemNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(_ComboBox_Systems, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(_Label_SystemSave, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                                .addComponent(_Button_SysPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_Button_SysNext, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(_TextField_SystemName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(_Label_SystemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                        .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_Label_RackNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(_ComboBox_RackNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_Label_RackName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                                    .addComponent(_Button_RackPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(_Button_RackNext, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(_TextField_RackName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _Panel_NamePanelLayout.createSequentialGroup()
                        .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(_Label_CompressorNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _Panel_NamePanelLayout.createSequentialGroup()
                                .addComponent(_ComboBox_CompressorNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                                .addComponent(_Button_CompPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_Button_CompNext, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(_Label_CompressorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_TextField_CompressorName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        _Panel_NamePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_TextField_CompressorName, _TextField_SystemName});

        _Panel_NamePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_Button_CompPrev, _Button_SysPrev});

        _Panel_NamePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_ComboBox_CompressorNumber, _ComboBox_RackNumber, _Label_CompressorNumber, _Label_RackNumber});

        _Panel_NamePanelLayout.setVerticalGroup(
            _Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Label_RackNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Label_RackName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_ComboBox_RackNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(_Panel_NamePanelLayout.createSequentialGroup()
                        .addComponent(_TextField_RackName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_Button_RackPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_Button_RackNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Label_CompressorNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Label_CompressorName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_ComboBox_CompressorNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_TextField_CompressorName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Button_CompPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Button_CompNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Label_SystemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Label_SystemName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_ComboBox_Systems, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_TextField_SystemName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Button_SysPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Button_SysNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_Label_SystemSave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        _Panel_NamePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {_Button_CompPrev, _Button_RackNext, _Button_RackPrev, _Button_SysPrev});

        _Panel_NamePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {_TextField_CompressorName, _TextField_RackName, _TextField_SystemName});

        _Label_StoreLogo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_StoreLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_StoreLogo.setText("Store Logo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(_Panel_Controls, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_Panel_NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(_Label_StoreLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_Panel_NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Panel_Controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(_Label_StoreLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * combo box for racks event
     *
     * @param evt
     */
    private void _ComboBox_RacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ComboBox_RacksActionPerformed
        // TODO add your handling code here:
        // Retrieve the settings for the rack
        _Label_RackSelected.setText(_ComboBox_Racks.getSelectedItem() + " Options");
        _ComboBox_SuctionGroups.setSelectedIndex(0);
        //System.out.println(_ComboBox_Racks.getSelectedIndex()); // index
        //System.out.println(_ComboBox_Racks.getSelectedItem()); // text
        this.loadRackOptions(_ComboBox_Racks.getSelectedIndex());

        // Update the display frame
        //System.out.println("combo box racks update");
        this.updateDisplay();
        // Done updating display frame
    }//GEN-LAST:event__ComboBox_RacksActionPerformed

    /**
     * combo box for suction group event
     *
     * @param evt
     */
    private void _ComboBox_SuctionGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ComboBox_SuctionGroupsActionPerformed
        // TODO add your handling code here:
        // Update suction settings
        _Label_SGSelected.setText(_ComboBox_SuctionGroups.getSelectedItem() + " Options");
        _TextField_SuctionGroupName.setText((String) _ComboBox_SuctionGroups.getSelectedItem());
        this.loadSuctionGroupOptions(_ComboBox_SuctionGroups.getSelectedIndex());

        // Update the display frame
        //System.out.println("combo box suction groups update");
        this.updateDisplay();
        // Done updating display frame
    }//GEN-LAST:event__ComboBox_SuctionGroupsActionPerformed

    /**
     * textfield for suctiongroup focus lost
     *
     * @param evt
     */
    private void _TextField_SuctionGroupNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__TextField_SuctionGroupNameFocusLost
        // TODO add your handling code here:
        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();
        String name = _TextField_SuctionGroupName.getText();
        store.getRackIndex(rackIndex).getSuctionGroupIndex(sgIndex).setName(name);
        this.loadComboBoxSuctionGroups(_ComboBox_SuctionGroups.getSelectedIndex());
        updateDisplay();
    }//GEN-LAST:event__TextField_SuctionGroupNameFocusLost

    /**
     * number of racks formatted text field property changed
     *
     * @param evt
     */
    private void _FormattedTF_NumRacksPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event__FormattedTF_NumRacksPropertyChange

        try {
            this.updateRackCount();
            addRacks();
            int rackIndex = _ComboBox_Racks.getSelectedIndex();
            this.updateRackNames(rackIndex);
            this.loadComboBoxRacks(_ComboBox_Racks.getSelectedIndex());

            // Update the display frame
            //System.out.println("slider num racks update");
            this.updateDisplay();
            // Done updating display frame
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event__FormattedTF_NumRacksPropertyChange

    /**
     * number of fans formatted text field property changed
     *
     * @param evt
     */
    private void _FormattedTF_NumFansPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event__FormattedTF_NumFansPropertyChange
        try {
            // update the current rack
            int rackIndex = _ComboBox_Racks.getSelectedIndex();
            this.updateFanCount();
            store.getRackIndex(rackIndex).setNumCondenserFans(numFans);

            // Update the display frame
            //System.out.println("slider condenser update");
            this.updateDisplay();
            // Done updating display frame
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event__FormattedTF_NumFansPropertyChange

    /**
     * number of suctiongroups formatted text field property changed
     *
     * @param evt
     */
    private void _FormattedTF_NumSGPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event__FormattedTF_NumSGPropertyChange
        // TODO add your handling code here:
        // Suction groups -> update combo box
        try {
            int rackIndex = _ComboBox_Racks.getSelectedIndex();
            this.updateSGCount();
            int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();
            String name = _TextField_SuctionGroupName.getText();
            store.getRackIndex(rackIndex).getSuctionGroupIndex(sgIndex).setName(name);
            store.getRackIndex(rackIndex).setNumSuctionGroups(numSG);
            this.loadComboBoxSuctionGroups(_ComboBox_SuctionGroups.getSelectedIndex());

            // Update the display frame
            //System.out.println("slider suction groups update");
            this.updateDisplay();
            // Done updating display frame
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event__FormattedTF_NumSGPropertyChange

    /**
     * number of comp formatted text field property changed
     *
     * @param evt
     */
    private void _FormattedTF_NumCompPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event__FormattedTF_NumCompPropertyChange

        try {
            this.updateCompCount();
            // update the compressor names fields
            this.updateCompressorNames(_ComboBox_CompressorNumber.getSelectedIndex());
            // Update the display frame
            //System.out.println("slider compressor update");
            this.updateDisplay();
            // Done updating display frame
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event__FormattedTF_NumCompPropertyChange

    /**
     * number of systems formatted text field property changed
     *
     * @param evt
     */
    private void _FormattedTF_NumSystemsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event__FormattedTF_NumSystemsPropertyChange

        try {
            this.updateSystemCount();
            // update the system names fields
            this.updateSystemNames(_ComboBox_Systems.getSelectedIndex());

            // Update the display frame
            //System.out.println("slider systems update");
            this.updateDisplay();
            // Done updating display frame
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event__FormattedTF_NumSystemsPropertyChange

    /**
     * combo box systems event
     *
     * @param evt
     */
    private void _ComboBox_SystemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ComboBox_SystemsActionPerformed
        // TODO add your handling code here:
        // Update the text
        int sysIndex = _ComboBox_Systems.getSelectedIndex();
        this.updateSystemNames(sysIndex);
        // Update the display frame
        this.updateDisplay();
        // Done updating display frame
    }//GEN-LAST:event__ComboBox_SystemsActionPerformed

    /**
     * previous system button click
     *
     * @param evt
     */
    private void _Button_SysPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_SysPrevActionPerformed
        // TODO add your handling code here:
        // Save the field
        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();
        int sysIndex = _ComboBox_Systems.getSelectedIndex();
        String name = _TextField_SystemName.getText();
        Rack r = store.getRackIndex(rackIndex);
        SuctionGroup sg = r.getSuctionGroup().get(sgIndex);
        sg.replaceSystemName(name, sysIndex);

        // Select previous name
        if (sysIndex > 0) {
            _ComboBox_Systems.setSelectedIndex(sysIndex - 1);
            _TextField_SystemName.setText(sg.getSystemNameIndex(sysIndex - 1));
        }

        // Update the display frame
        //System.out.println("button prev update");
        this.updateDisplay();
        // Done updating display frame
        // Highlight the text field
        this._TextField_SystemName.requestFocus();
        this._TextField_SystemName.selectAll();
    }//GEN-LAST:event__Button_SysPrevActionPerformed

    /**
     * next system button click
     *
     * @param evt
     */
    private void _Button_SysNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_SysNextActionPerformed
        // TODO add your handling code here:
        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();
        int sysIndex = _ComboBox_Systems.getSelectedIndex();
        String name = _TextField_SystemName.getText();
        Rack r = store.getRackIndex(rackIndex);
        SuctionGroup sg = r.getSuctionGroup().get(sgIndex);
        sg.replaceSystemName(name, sysIndex);
        // Select previous name
        if (sysIndex < sg.getNumSystems() - 1) {
            _ComboBox_Systems.setSelectedIndex(sysIndex + 1);
            _TextField_SystemName.setText(sg.getSystemNameIndex(sysIndex + 1));
        }

        // Update the display frame
        //System.out.println("button next update");
        this.updateDisplay();
        // Done updating display frame
        // Highlight the text field
        this._TextField_SystemName.requestFocus();
        this._TextField_SystemName.selectAll();
    }//GEN-LAST:event__Button_SysNextActionPerformed

    /**
     * next comp button click
     *
     * @param evt
     */
    private void _Button_CompNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_CompNextActionPerformed
        // TODO add your handling code here:
        // Save the field
        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();
        int compIndex = _ComboBox_CompressorNumber.getSelectedIndex();
        String name = _TextField_CompressorName.getText();
        Rack r = store.getRackIndex(rackIndex);
        SuctionGroup sg = r.getSuctionGroup().get(sgIndex);
        sg.replaceCompressorName(name, compIndex);

        // Select previous name
        if (compIndex < sg.getNumCompressors() - 1) {
            _ComboBox_CompressorNumber.setSelectedIndex(compIndex + 1);
            _TextField_CompressorName.setText(sg.getCompressorNameIndex(compIndex + 1));
        }

        // Update the display frame
        //System.out.println("button prev update");
        this.updateDisplay();
        // Done updating display frame
        // Highlight the text field
        this._TextField_CompressorName.requestFocus();
        this._TextField_CompressorName.selectAll();
    }//GEN-LAST:event__Button_CompNextActionPerformed

    /**
     * prev comp button click
     *
     * @param evt
     */
    private void _Button_CompPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_CompPrevActionPerformed
        // TODO add your handling code here:
        // Save the field
        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();
        int compIndex = _ComboBox_CompressorNumber.getSelectedIndex();
        String name = _TextField_CompressorName.getText();
        Rack r = store.getRackIndex(rackIndex);
        SuctionGroup sg = r.getSuctionGroup().get(sgIndex);
        sg.replaceCompressorName(name, compIndex);

        // Select previous name
        if (compIndex > 0) {
            _ComboBox_CompressorNumber.setSelectedIndex(compIndex - 1);
            _TextField_CompressorName.setText(sg.getCompressorNameIndex(compIndex - 1));
        }

        // Update the display frame
        //System.out.println("button prev update");
        this.updateDisplay();
        // Done updating display frame
        // Highlight the text field
        this._TextField_CompressorName.requestFocus();
        this._TextField_CompressorName.selectAll();
    }//GEN-LAST:event__Button_CompPrevActionPerformed

    /**
     * combo box compressor event
     *
     * @param evt
     */
    private void _ComboBox_CompressorNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ComboBox_CompressorNumberActionPerformed
        // TODO add your handling code here:
        // Update the text
        int compIndex = _ComboBox_CompressorNumber.getSelectedIndex();
        this.updateCompressorNames(compIndex);
        this.updateDisplay();
        // Done updating display frame
    }//GEN-LAST:event__ComboBox_CompressorNumberActionPerformed

    /**
     * next rack button click
     *
     * @param evt
     */
    private void _Button_RackNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_RackNextActionPerformed
        // TODO add your handling code here:
        // Save the field
        int rackIndex = _ComboBox_RackNumber.getSelectedIndex();
        String name = _TextField_RackName.getText();
        Rack r = store.getRackIndex(rackIndex);
        r.setName(name);

        // Select previous name
        if (rackIndex < numRacks - 1) {
            _ComboBox_RackNumber.setSelectedIndex(rackIndex + 1);
            _TextField_RackName.setText(store.getRackIndex(rackIndex+1).getName());
        }

        // Update the display frame
        //System.out.println("button prev update");
        this.loadComboBoxRacks(_ComboBox_Racks.getSelectedIndex());
        this.updateDisplay();
        // Done updating display frame
        // Highlight the text field
        this._TextField_RackName.requestFocus();
        this._TextField_RackName.selectAll();
    }//GEN-LAST:event__Button_RackNextActionPerformed

    /**
     * prev rack button click
     *
     * @param evt
     */
    private void _Button_RackPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_RackPrevActionPerformed
        // TODO add your handling code here:
        // Save the field
        int rackIndex = _ComboBox_RackNumber.getSelectedIndex();

        String name = _TextField_RackName.getText();
        Rack r = store.getRackIndex(rackIndex);
        r.setName(name);

        // Select previous name
        if (rackIndex > 0) {
            _ComboBox_RackNumber.setSelectedIndex(rackIndex - 1);
            _TextField_RackName.setText(store.getRackIndex(rackIndex - 1).getName());
        }

        // Update the display frame
        //System.out.println("button prev update");
        this.loadComboBoxRacks(_ComboBox_Racks.getSelectedIndex());
        this.updateDisplay();
        // Done updating display frame
        // Highlight the text field
        this._TextField_RackName.requestFocus();
        this._TextField_RackName.selectAll();
    }//GEN-LAST:event__Button_RackPrevActionPerformed

    /**
     * combo box rack event
     *
     * @param evt
     */
    private void _ComboBox_RackNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ComboBox_RackNumberActionPerformed
        // TODO add your handling code here:
        // Update the text
        int rackIndex = _ComboBox_RackNumber.getSelectedIndex();
        this.updateRackNames(rackIndex);
        // Update the display frame
        this.updateDisplay();
        // Done updating display frame
    }//GEN-LAST:event__ComboBox_RackNumberActionPerformed

    private void _TextField_SiteNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__TextField_SiteNameFocusLost
        // TODO add your handling code here:
        store.setStoreName(_TextField_SiteName.getText());
        this.updateDisplay();
    }//GEN-LAST:event__TextField_SiteNameFocusLost

    /**
     * loads the combo box for racks
     *
     * @param prevSelectedIndex the previously selected index of the combo box
     */
    public void loadComboBoxRacks(int prevSelectedIndex) {

        // Update the combo box
        _ComboBox_Racks.setModel(new javax.swing.DefaultComboBoxModel(getRackNames()));

        if (prevSelectedIndex <= numRacks - 1) {
            _ComboBox_Racks.setSelectedIndex(prevSelectedIndex);
        } else {
            _ComboBox_Racks.setSelectedIndex(0);
        }

        _Label_RackSelected.setText(_ComboBox_Racks.getSelectedItem() + " Options");

        this.loadRackOptions(_ComboBox_Racks.getSelectedIndex());

    }

    /**
     * loads the options for racks
     *
     * @param index the previously selected index of the combo box
     */
    public void loadRackOptions(int index) {

        // Load all the options for the index'd rack
        Rack cr = store.getRackIndex(index);       
        numFans = cr.getNumCondenserFans();
        numSG = cr.getNumSuctionGroups();
        _FormattedTF_NumFans.setText("" + numFans);
        _FormattedTF_NumSG.setText("" + numSG);
        this.loadComboBoxSuctionGroups(0);
    }

    /**
     * loads the combo box for suction groups
     *
     * @param prevSelectedIndex the previously selected index of the combo box
     */
    public void loadComboBoxSuctionGroups(int prevSelectedIndex) {

        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgNum = store.getRackIndex(rackIndex).getNumSuctionGroups();

        String[] sgNames = store.getRackIndex(rackIndex).getSuctionGroupNames();

        // Update the combo box
        _ComboBox_SuctionGroups.setModel(new javax.swing.DefaultComboBoxModel(sgNames));

        if (prevSelectedIndex <= sgNum - 1) {
            _ComboBox_SuctionGroups.setSelectedIndex(prevSelectedIndex);
        } else {
            _ComboBox_SuctionGroups.setSelectedIndex(0);
        }

        _Label_SGSelected.setText(_ComboBox_SuctionGroups.getSelectedItem() + " Options");

        this.loadSuctionGroupOptions(_ComboBox_SuctionGroups.getSelectedIndex());

    }

    /**
     * loads the options for suction group
     *
     * @param index the previously selected index of the combo box
     */
    public void loadSuctionGroupOptions(int index) {

        // Load the suction group 
        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();

        SuctionGroup sg = store.getRackIndex(rackIndex).getSuctionGroupIndex(sgIndex);
        numComp = sg.getNumCompressors();
        numSystems = sg.getNumSystems();
        _FormattedTF_NumComp.setText("" + numComp);
        _FormattedTF_NumSystems.setText("" + numSystems);

        this.updateCompressorNames(_ComboBox_CompressorNumber.getSelectedIndex());
        this.updateSystemNames(_ComboBox_Systems.getSelectedIndex());
    }

    /**
     * updates the compressor names
     *
     * @param prevSelectedIndex previously selected index of the combo box
     */
    public void updateCompressorNames(int prevSelectedIndex) {
        // first update the combo box indicating what system names can be edited
        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();
        int compIndex = _ComboBox_CompressorNumber.getSelectedIndex();

        SuctionGroup sg = store.getRackIndex(rackIndex).getSuctionGroupIndex(sgIndex);

        String[] cmp = new String[numComp];
        for (int i = 0; i < numComp; i++) {
            cmp[i] = "Compressor " + (i + 1);
        }
        _ComboBox_CompressorNumber.setModel(new javax.swing.DefaultComboBoxModel(cmp));
        if (prevSelectedIndex <= numComp - 1) {
            _ComboBox_CompressorNumber.setSelectedIndex(prevSelectedIndex);
        } else {
            _ComboBox_CompressorNumber.setSelectedIndex(0);
        }

        // Combo box updated, now add any system names that need to be added
        sg.addCompressorNames(Math.abs(Integer.parseInt(_FormattedTF_NumComp.getText())));
        // System drop box is set now update the text field 

        _TextField_CompressorName.setText(sg.getCompressorNameIndex(compIndex));

    }

    /**
     * updates the rack names
     *
     * @param prevSelectedIndex previously selected index of the combo box
     */
    public void updateRackNames(int prevSelectedIndex) {
        // first update the combo box indicating what system names can be edited

        String[] rk = new String[numRacks];
        for (int i = 0; i < numRacks; i++) {
            rk[i] = "Rack " + (i + 1);
        }
        _ComboBox_RackNumber.setModel(new javax.swing.DefaultComboBoxModel(rk));
        if (prevSelectedIndex <= numRacks - 1) {
            _ComboBox_RackNumber.setSelectedIndex(prevSelectedIndex);
        } else {
            _ComboBox_RackNumber.setSelectedIndex(0);
        }

        // Combo box updated, now add any rack that need to be added
        addRacks();
        // System drop box is set now update the text field 

        _TextField_RackName.setText(store.getRackIndex(_ComboBox_RackNumber.getSelectedIndex()).getName());

    }

    /**
     * adds racks if needed to
     */
    public void addRacks() {
        int size = store.getRacks().size();
        int toAdd = numRacks - size;

        for (int i = 0; i < toAdd; i++) {
            store.addRack(new Rack("Rack " + (size + i + 1)));
        }

    }

    /**
     * updates the system names
     *
     * @param prevSelectedIndex previously selected index of the combo box
     */
    public void updateSystemNames(int prevSelectedIndex) {
        // first update the combo box indicating what system names can be edited
        int rackIndex = _ComboBox_Racks.getSelectedIndex();
        int sgIndex = _ComboBox_SuctionGroups.getSelectedIndex();
        int systemIndex = _ComboBox_Systems.getSelectedIndex();
        SuctionGroup sg = store.getRackIndex(rackIndex).getSuctionGroupIndex(sgIndex);
        String[] sys = new String[numSystems];
        for (int i = 0; i < numSystems; i++) {
            sys[i] = "System " + (i + 1);
        }
        _ComboBox_Systems.setModel(new javax.swing.DefaultComboBoxModel(sys));
        if (prevSelectedIndex <= numSystems - 1) {
            _ComboBox_Systems.setSelectedIndex(prevSelectedIndex);
        } else {
            _ComboBox_Systems.setSelectedIndex(0);
        }

        // Combo box updated, now add any system names that need to be added
        sg.addSystemNames(Math.abs(Integer.parseInt(_FormattedTF_NumSystems.getText())));
        // System drop box is set now update the text field 

        _TextField_SystemName.setText(sg.getSystemNameIndex(systemIndex));

    }

    /**
     * removes the string of the store logo 
     */
    public void removeStoreLogo() {
        store.setImgStr("");
        _Label_StoreLogo.setIcon(null);
        _Label_StoreLogo.setText("Store Logo");
    }

    /**
     * updates the store logo based on the string stored
     */
    public void updateStoreLogo() {
        try {
            System.out.println("Image path: " + store.getImgStr());
            ImageIcon icon = new ImageIcon(store.getImgStr());
            _Label_StoreLogo.setText("");
            _Label_StoreLogo.setIcon(icon);
        } catch (Exception e) {
            _Label_StoreLogo.setText("Problem loading file: " + store.getImgStr());
        }
    }

    /**
     * updates the store logo
     *
     * @param img file path of the logo
     */
    public void updateStoreLogo(String img) {
        try {
            store.setImgStr(img);
            ImageIcon icon = new ImageIcon(store.getImgStr());
            _Label_StoreLogo.setText("");
            _Label_StoreLogo.setIcon(icon);
        } catch (Exception e) {
            _Label_StoreLogo.setText("Problem loading file: " + store.getImgStr());
        }
    }

    /**
     * gets the rack names from the array list
     *
     * @return string array of the rack names
     */
    public String[] getRackNames() {
        String[] names = new String[numRacks];
        for (int i = 0; i < numRacks; i++) {
            names[i] = store.getRackIndex(i).getName();
        }
        return names;
    }

    /**
     * updates the main frame display with the stored information
     */
    public void updateDisplay() {        
        mf.updateDisplay(store);
    }

    /**
     * update the rack count based on the text field
     *
     * @throws NumberFormatException for badly formatted text fields
     */
    public void updateRackCount() throws NumberFormatException {

        numRacks = Math.abs(Integer.parseInt(_FormattedTF_NumRacks.getText()));
        if (numRacks > 15) {
            numRacks = 15;
            _FormattedTF_NumRacks.setValue(new Integer("15"));
        } else if (numRacks == 0) {
            _FormattedTF_NumRacks.setValue(1);
            _FormattedTF_NumRacks.setValue(new Integer("1"));
        } else {
            _FormattedTF_NumRacks.setValue(numRacks);
        }
        store.setNumRacks(numRacks);

    }

    /**
     * update the fan count based on the text field
     *
     * @throws NumberFormatException for badly formatted text fields
     */
    public void updateFanCount() throws NumberFormatException {
        numFans = Math.abs(Integer.parseInt(_FormattedTF_NumFans.getText()));
        if (numFans > 100) {
            numFans = 100;
            _FormattedTF_NumFans.setValue(new Integer("100"));
        } else if (numFans == 0) {
            _FormattedTF_NumFans.setValue(1);
            _FormattedTF_NumFans.setValue(new Integer("1"));
        } else {
            _FormattedTF_NumFans.setValue(numFans);
        }
        store.getRackIndex(_ComboBox_Racks.getSelectedIndex()).setNumCondenserFans(numFans);
        
    }

    /**
     * update the suction group count based on the text field
     *
     * @throws NumberFormatException for badly formatted text fields
     */
    public void updateSGCount() throws NumberFormatException {
        numSG = Math.abs(Integer.parseInt(_FormattedTF_NumSG.getText()));
        if (numSG > 15) {
            numSG = 15;
            _FormattedTF_NumSG.setValue(new Integer("15"));
        } else if (numSG == 0) {
            _FormattedTF_NumSG.setValue(1);
            _FormattedTF_NumSG.setValue(new Integer("1"));
        } else {
            _FormattedTF_NumSG.setValue(numSG);
        }
        store.getRackIndex(_ComboBox_Racks.getSelectedIndex()).setNumSuctionGroups(numSG);
    }

    /**
     * update the comp count based on the text field
     *
     * @throws NumberFormatException for badly formatted text fields
     */
    public void updateCompCount() throws NumberFormatException {
        numComp = Math.abs(Integer.parseInt(_FormattedTF_NumComp.getText()));
        if (numComp > 100) {
            numComp = 100;
            _FormattedTF_NumComp.setValue(new Integer("100"));
        } else if (numComp == 0) {
            _FormattedTF_NumComp.setValue(1);
            _FormattedTF_NumComp.setValue(new Integer("1"));
        } else {
            _FormattedTF_NumComp.setValue(numComp);
        }
        store.getRackIndex(_ComboBox_Racks.getSelectedIndex()).getSuctionGroupIndex(_ComboBox_SuctionGroups.getSelectedIndex()).setNumCompressors(numComp);
    }

    /**
     * update the system count based on the text field
     *
     * @throws NumberFormatException for badly formatted text fields
     */
    public void updateSystemCount() throws NumberFormatException {
        numSystems = Math.abs(Integer.parseInt(_FormattedTF_NumSystems.getText()));
        if (numSystems > 100) {
            numSystems = 100;
            _FormattedTF_NumSystems.setValue(new Integer("100"));
        } else if (numSystems == 0) {
            _FormattedTF_NumSystems.setValue(1);
            _FormattedTF_NumSystems.setValue(new Integer("1"));
        } else {
            _FormattedTF_NumSystems.setValue(numSystems);
        }
        store.getRackIndex(_ComboBox_Racks.getSelectedIndex()).getSuctionGroupIndex(_ComboBox_SuctionGroups.getSelectedIndex()).setNumSystems(numSystems);
    }

    /**_ComboBox_SuctionGroups.getSelectedIndex()).setNumSystems(numSystems);
    }

    /**
     * Loads the store from the menu
     *
     * @param store store
     */
    public void loadStore(Store store) {
        this.store = store;
        this.updateRackDisplay();
        
    }

    /**
     * updates the rack display
     */
    public void updateRackDisplay() {

        _TextField_SiteName.setText(this.store.getStoreName());
        numRacks = this.store.getNumRacks();
        _FormattedTF_NumRacks.setText(String.valueOf(numRacks));
        this.updateStoreLogo();
        this.updateRackNames(0);
        this.loadComboBoxRacks(0);
        this.loadRackOptions(0);
        this.updateDisplay();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _Button_CompNext;
    private javax.swing.JButton _Button_CompPrev;
    private javax.swing.JButton _Button_RackNext;
    private javax.swing.JButton _Button_RackPrev;
    private javax.swing.JButton _Button_SysNext;
    private javax.swing.JButton _Button_SysPrev;
    private javax.swing.JComboBox _ComboBox_CompressorNumber;
    private javax.swing.JComboBox _ComboBox_RackNumber;
    private javax.swing.JComboBox _ComboBox_Racks;
    private javax.swing.JComboBox _ComboBox_SuctionGroups;
    private javax.swing.JComboBox _ComboBox_Systems;
    private javax.swing.JFormattedTextField _FormattedTF_NumComp;
    private javax.swing.JFormattedTextField _FormattedTF_NumFans;
    private javax.swing.JFormattedTextField _FormattedTF_NumRacks;
    private javax.swing.JFormattedTextField _FormattedTF_NumSG;
    private javax.swing.JFormattedTextField _FormattedTF_NumSystems;
    private javax.swing.JLabel _Label_CompressorName;
    private javax.swing.JLabel _Label_CompressorNumber;
    private javax.swing.JLabel _Label_Compressors;
    private javax.swing.JLabel _Label_CondenserFans;
    private javax.swing.JLabel _Label_NumberRacks;
    private javax.swing.JLabel _Label_NumberSuctionGroups;
    private javax.swing.JLabel _Label_NumberSystems;
    private javax.swing.JLabel _Label_RackName;
    private javax.swing.JLabel _Label_RackNumber;
    private javax.swing.JLabel _Label_RackSelected;
    private javax.swing.JLabel _Label_SGSelected;
    private javax.swing.JLabel _Label_Site;
    private javax.swing.JLabel _Label_StoreLogo;
    private javax.swing.JLabel _Label_SuctionGroupName;
    private javax.swing.JLabel _Label_SuctionGroupOptions;
    private javax.swing.JLabel _Label_SystemName;
    private javax.swing.JLabel _Label_SystemNumber;
    private javax.swing.JLabel _Label_SystemSave;
    private javax.swing.JLabel _Label_Title;
    private javax.swing.JPanel _Panel_Controls;
    private javax.swing.JPanel _Panel_NamePanel;
    private javax.swing.JTextField _TextField_CompressorName;
    private javax.swing.JTextField _TextField_RackName;
    private javax.swing.JTextField _TextField_SiteName;
    private javax.swing.JTextField _TextField_SuctionGroupName;
    private javax.swing.JTextField _TextField_SystemName;
    // End of variables declaration//GEN-END:variables

}
