/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel.creator;

import java.awt.AWTException;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author EricGummerson
 */
public class MainFrame extends JFrame {

    private final PanelCreator main;
    public DisplayFrame displayFrame;
    public SettingsFrame settingsFrame;
    public ControlsPanel controlPanel;
    public String img;

    /**
     * Creates new form MainFrame
     *
     * @param main
     */
    public MainFrame(PanelCreator main) {
        this.main = main;
        initComponents();
        initPanels();
        img = "";
    }

    private void initPanels() {

        controlPanel = new ControlsPanel(this);
        displayFrame = new DisplayFrame(this);
        settingsFrame = new SettingsFrame(this);

        // Load the main panel        
        controlPanel.setVisible(true);
        displayFrame.setVisible(true);
        controlPanel.updateDisplay();
        // add it to the frame   
        this.setLayout(new BorderLayout());
        this.add(controlPanel, BorderLayout.CENTER);

    }

    public void updateDisplaySize(Dimension d) {
        if (settingsFrame != null) {
            settingsFrame.setDim(d);
        }
    }

    public void updateDisplaySize(int width, int height) {
        //displayFrame.setNewSize(width, height);
        displayFrame.setSize(width, height);
    }

    public void updateFont(Font f) {
        displayFrame.updateFont(f);
    }

    public void updateBorder(Border b) {
        displayFrame.updateBorder(b);
    }

    public void displayPanel(int width, int height) {
        displayFrame.setNewSize(width, height);
        if (!displayFrame.isVisible()) {
            controlPanel.updateDisplay();
            displayFrame.setVisible(true);
        } else {
            displayFrame.setVisible(false);
        }
    }

    public void displaySettings() {
        if (!settingsFrame.isVisible()) {
            settingsFrame.setVisible(true);
        } else {
            settingsFrame.setVisible(false);
        }
    }

    public void hideSettings() {
        settingsFrame.setVisible(false);
    }

    public void updateDisplay(Rack[] racks, int numRacks, String sn, String[] rn) {
        Font f = settingsFrame.getFontData();
        Border b = settingsFrame.getBorder();
        displayFrame.updateDisplays(racks, numRacks, f, b, img, sn, rn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _FileChooser_Img = new javax.swing.JFileChooser();
        _FileChooser_Save = new javax.swing.JFileChooser();
        _MenuBar_Menus = new javax.swing.JMenuBar();
        _Menu_File = new javax.swing.JMenu();
        _MenuItem_Save = new javax.swing.JMenuItem();
        _MenuItem_Close = new javax.swing.JMenuItem();
        _Menu_Settings = new javax.swing.JMenu();
        _MenuItem_Settings = new javax.swing.JMenuItem();
        _Menu_View = new javax.swing.JMenu();
        _MenuItem_ViewPanel = new javax.swing.JMenuItem();
        _Menu_Image = new javax.swing.JMenu();
        _MenuItem_OpenImage = new javax.swing.JMenuItem();
        _MenuItem_RemoveImage = new javax.swing.JMenuItem();

        _FileChooser_Img.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        _FileChooser_Img.setApproveButtonText("Save");
        _FileChooser_Img.setApproveButtonToolTipText("Saves the file");
        _FileChooser_Img.setDialogTitle("Open image file for the store logo");
        _FileChooser_Img.setFileFilter(new ImageFilter());

        _FileChooser_Save.setApproveButtonText("Save");
        _FileChooser_Save.setDialogTitle("Directory to save");
        _FileChooser_Save.setFileFilter(new FileNameExtensionFilter("Image files (.png, .jpg, .gif)", new String[]{"jpg", "gif", "png"}));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Creator");
        setResizable(false);

        _Menu_File.setText("File");

        _MenuItem_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        _MenuItem_Save.setText("Save display as Picture");
        _MenuItem_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MenuItem_SaveActionPerformed(evt);
            }
        });
        _Menu_File.add(_MenuItem_Save);

        _MenuItem_Close.setText("Exit");
        _MenuItem_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MenuItem_CloseActionPerformed(evt);
            }
        });
        _Menu_File.add(_MenuItem_Close);

        _MenuBar_Menus.add(_Menu_File);

        _Menu_Settings.setText("Settings");

        _MenuItem_Settings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        _MenuItem_Settings.setText("Display Settings");
        _MenuItem_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MenuItem_SettingsActionPerformed(evt);
            }
        });
        _Menu_Settings.add(_MenuItem_Settings);

        _MenuBar_Menus.add(_Menu_Settings);

        _Menu_View.setText("View");

        _MenuItem_ViewPanel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        _MenuItem_ViewPanel.setText("View Panels");
        _MenuItem_ViewPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MenuItem_ViewPanelActionPerformed(evt);
            }
        });
        _Menu_View.add(_MenuItem_ViewPanel);

        _MenuBar_Menus.add(_Menu_View);

        _Menu_Image.setText("Image");

        _MenuItem_OpenImage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        _MenuItem_OpenImage.setText("Open Image File");
        _MenuItem_OpenImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MenuItem_OpenImageActionPerformed(evt);
            }
        });
        _Menu_Image.add(_MenuItem_OpenImage);

        _MenuItem_RemoveImage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        _MenuItem_RemoveImage.setText("Remove Image");
        _MenuItem_RemoveImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MenuItem_RemoveImageActionPerformed(evt);
            }
        });
        _Menu_Image.add(_MenuItem_RemoveImage);

        _MenuBar_Menus.add(_Menu_Image);

        setJMenuBar(_MenuBar_Menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _MenuItem_ViewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MenuItem_ViewPanelActionPerformed
        // TODO add your handling code here:
        int width = settingsFrame.getDisplayWidth();
        int height = settingsFrame.getDisplayHeight();
        displayPanel(width, height);
    }//GEN-LAST:event__MenuItem_ViewPanelActionPerformed

    private void _MenuItem_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MenuItem_SettingsActionPerformed
        // TODO add your handling code here:
        // Open settings
        displaySettings();
    }//GEN-LAST:event__MenuItem_SettingsActionPerformed

    private void _MenuItem_OpenImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MenuItem_OpenImageActionPerformed
        // TODO add your handling code here:
        int returnVal = _FileChooser_Img.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = _FileChooser_Img.getSelectedFile();

            // What to do with the file, e.g. display it in a TextArea
            System.out.println("File: " + file.getAbsolutePath());
            img = file.getAbsolutePath();
            displayFrame.updateLogo(img);
            controlPanel.updateStoreLogo(img);

        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event__MenuItem_OpenImageActionPerformed

    private void _MenuItem_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MenuItem_CloseActionPerformed
        // TODO add your handling code here:
        main.close();
    }//GEN-LAST:event__MenuItem_CloseActionPerformed

    private void _MenuItem_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MenuItem_SaveActionPerformed
        // TODO add your handling code here:

        int returnVal = _FileChooser_Save.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String fn = _FileChooser_Save.getSelectedFile().toString();
            if (!fn.endsWith(".png") || !fn.endsWith(".jpg") || !fn.endsWith(".gif")) {
                fn += ".png";
            }
            // What to do with the file, e.g. display it in a TextArea

            try {
                BufferedImage bi = ScreenImage.createImage(displayFrame.getCurrentPane());
                ScreenImage.writeImage(bi, fn);
                //ScreenImage.createImage();
            } catch (AWTException | IOException e) {
                System.out.println("Error " + e.getMessage());
            }

        } else {
            System.out.println("File access cancelled by user.");
        }

    }//GEN-LAST:event__MenuItem_SaveActionPerformed

    private void _MenuItem_RemoveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MenuItem_RemoveImageActionPerformed
        // TODO add your handling code here:

        displayFrame.updateLogo();
        controlPanel.updateStoreLogo();

    }//GEN-LAST:event__MenuItem_RemoveImageActionPerformed

    //================================================================
    //================================================================
    //                      Functions
    //================================================================
    //================================================================

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser _FileChooser_Img;
    private javax.swing.JFileChooser _FileChooser_Save;
    private javax.swing.JMenuBar _MenuBar_Menus;
    private javax.swing.JMenuItem _MenuItem_Close;
    private javax.swing.JMenuItem _MenuItem_OpenImage;
    private javax.swing.JMenuItem _MenuItem_RemoveImage;
    private javax.swing.JMenuItem _MenuItem_Save;
    private javax.swing.JMenuItem _MenuItem_Settings;
    private javax.swing.JMenuItem _MenuItem_ViewPanel;
    private javax.swing.JMenu _Menu_File;
    private javax.swing.JMenu _Menu_Image;
    private javax.swing.JMenu _Menu_Settings;
    private javax.swing.JMenu _Menu_View;
    // End of variables declaration//GEN-END:variables
}
