/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel.creator;

import javafx.scene.control.ComboBox;
import javax.swing.ComboBoxModel;

/**
 *
 * @author EricGummerson
 */
public class MeterPanel extends javax.swing.JPanel {

    public ModbusPanel mp;
    public String name;
    public int type;
    public Slave slave;

    /**
     * Creates new form MeterPanel
     *
     * @param mp
     * @param slaveNumber
     * @param type
     */
    public MeterPanel(ModbusPanel mp, int slaveNumber, int type) {        
        initComponents();
        this.mp = mp;
        this.name = "Slave " + slaveNumber;
        _Label_Slave1.setText(this.name);
        this.type = type;
        // 3 phase
        if (type == 1) {
            slave = new Slave(1, name);            
        } else {
            // 1 phase
            slave = new Slave(2, name);
            _ComboBox_Reg2.setEnabled(false);
            _ComboBox_Reg3.setEnabled(false);
        }
    }
    
    public void updateModelList(ComboBoxModel cm){
        _ComboBox_Reg1.setModel(cm);
        _ComboBox_Reg2.setModel(cm);
        _ComboBox_Reg3.setModel(cm);
    }

    public String getMeterName() {
        return name;
    }

    public void setMeterName(String name) {
        this.name = name;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        _Panel_Slave1 = new javax.swing.JPanel();
        _Label_Slave1 = new javax.swing.JLabel();
        _ComboBox_Slave1 = new javax.swing.JComboBox();
        _ComboBox_Reg1 = new javax.swing.JComboBox();
        _ComboBox_Reg2 = new javax.swing.JComboBox();
        _ComboBox_Reg3 = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        _Label_Slave1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        _Label_Slave1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_Slave1.setText("Slave 1");

        _ComboBox_Slave1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        _ComboBox_Slave1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3 Phase", "1 Phase" }));
        _ComboBox_Slave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ComboBox_Slave1ActionPerformed(evt);
            }
        });

        _ComboBox_Reg1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        _ComboBox_Reg1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty" }));

        _ComboBox_Reg2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        _ComboBox_Reg2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty" }));

        _ComboBox_Reg3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        _ComboBox_Reg3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty" }));

        javax.swing.GroupLayout _Panel_Slave1Layout = new javax.swing.GroupLayout(_Panel_Slave1);
        _Panel_Slave1.setLayout(_Panel_Slave1Layout);
        _Panel_Slave1Layout.setHorizontalGroup(
            _Panel_Slave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_Panel_Slave1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_Panel_Slave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_Label_Slave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_ComboBox_Slave1, 0, 99, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(_Panel_Slave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _Panel_Slave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_ComboBox_Reg2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_ComboBox_Reg3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_ComboBox_Reg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        _Panel_Slave1Layout.setVerticalGroup(
            _Panel_Slave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_Panel_Slave1Layout.createSequentialGroup()
                .addGroup(_Panel_Slave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_ComboBox_Reg1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(_Panel_Slave1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(_Label_Slave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_Panel_Slave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_ComboBox_Slave1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(_ComboBox_Reg2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_ComboBox_Reg3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_Panel_Slave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_Panel_Slave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void _ComboBox_Slave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ComboBox_Slave1ActionPerformed
        // TODO add your handling code here:
        if(_ComboBox_Slave1.getSelectedIndex() == 0){
            _ComboBox_Reg1.setEnabled(true);
            _ComboBox_Reg2.setEnabled(true);
            _ComboBox_Reg3.setEnabled(true);
            this.type = 1;
        }else {
            _ComboBox_Reg1.setEnabled(false);
            _ComboBox_Reg2.setEnabled(false);
            _ComboBox_Reg3.setEnabled(false);
            this.type = 2;
        }
    }//GEN-LAST:event__ComboBox_Slave1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox _ComboBox_Reg1;
    private javax.swing.JComboBox _ComboBox_Reg2;
    private javax.swing.JComboBox _ComboBox_Reg3;
    private javax.swing.JComboBox _ComboBox_Slave1;
    private javax.swing.JLabel _Label_Slave1;
    private javax.swing.JPanel _Panel_Slave1;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
}
