/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel.creator;

/**
 *
 * @author EricGummerson
 */
public class RackSettingsFrame extends javax.swing.JFrame {

    ControlsPanel cp;
    int maxRacks, maxFans, maxSG, maxComp, maxSystems;
    /**
     * Creates new form RackSettings
     * @param cp
     */
    public RackSettingsFrame(ControlsPanel cp) {
        initComponents();
        this.cp = cp;
        maxRacks = 5;
        maxSG = 6;
        maxFans = maxComp = maxSystems = 20;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        _Label_MaxRacks = new javax.swing.JLabel();
        _Label_RackSettings = new javax.swing.JLabel();
        _FormattedTF_MaxRacks = new javax.swing.JFormattedTextField();
        _Label_MaxFans = new javax.swing.JLabel();
        _FormattedTF_MaxFans = new javax.swing.JFormattedTextField();
        _Label_MaxSG = new javax.swing.JLabel();
        _FormattedTF_MaxSG = new javax.swing.JFormattedTextField();
        _Label_MaxComp = new javax.swing.JLabel();
        _FormattedTF_MaxComp = new javax.swing.JFormattedTextField();
        _Label_MaxSystems = new javax.swing.JLabel();
        _FormattedTF_MaxSystems = new javax.swing.JFormattedTextField();
        _Button_Save = new javax.swing.JButton();
        _Button_Defaults = new javax.swing.JButton();
        _Label_Log = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setMinimumSize(new java.awt.Dimension(431, 493));
        setResizable(false);

        _Label_MaxRacks.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_MaxRacks.setText("Max number of Racks                            Max 20");

        _Label_RackSettings.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _Label_RackSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _Label_RackSettings.setText("Rack Slider Settings");

        _FormattedTF_MaxRacks.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_MaxRacks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_MaxRacks.setText("5");

        _Label_MaxFans.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_MaxFans.setText("Max number of Cond. Fans                    Max 100");

        _FormattedTF_MaxFans.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_MaxFans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_MaxFans.setText("20");

        _Label_MaxSG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_MaxSG.setText("Max number of Suction Groups              Max 20");

        _FormattedTF_MaxSG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_MaxSG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_MaxSG.setText("6");

        _Label_MaxComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_MaxComp.setText("Max number of Compressors                  Max 100");

        _FormattedTF_MaxComp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_MaxComp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_MaxComp.setText("20");

        _Label_MaxSystems.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _Label_MaxSystems.setText("Max number of Systems                        Max 100");

        _FormattedTF_MaxSystems.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        _FormattedTF_MaxSystems.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _FormattedTF_MaxSystems.setText("20");

        _Button_Save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _Button_Save.setText("Save");
        _Button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_SaveActionPerformed(evt);
            }
        });

        _Button_Defaults.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _Button_Defaults.setText("Defaults");
        _Button_Defaults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_DefaultsActionPerformed(evt);
            }
        });

        _Label_Log.setText("Log");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_Label_MaxRacks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(_Button_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(_Label_MaxFans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_Label_MaxSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_Label_MaxComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_Label_MaxSystems, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                            .addComponent(_Button_Defaults, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_FormattedTF_MaxRacks, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_FormattedTF_MaxFans, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_FormattedTF_MaxSG, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_FormattedTF_MaxComp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_FormattedTF_MaxSystems, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_Label_RackSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(_Label_Log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(_Label_RackSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_Label_MaxRacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_FormattedTF_MaxRacks, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_Label_MaxFans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_FormattedTF_MaxFans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_Label_MaxSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_FormattedTF_MaxSG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_Label_MaxComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_FormattedTF_MaxComp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_Label_MaxSystems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_FormattedTF_MaxSystems, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(_Label_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(_Button_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_Button_Defaults, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void _Button_DefaultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_DefaultsActionPerformed
        // TODO add your handling code here:
        _FormattedTF_MaxRacks.setText("5");
        _FormattedTF_MaxFans.setText("20");
        _FormattedTF_MaxSG.setText("6");
        _FormattedTF_MaxComp.setText("20");
        _FormattedTF_MaxSystems.setText("20");
        updateControlsPanel();
    }//GEN-LAST:event__Button_DefaultsActionPerformed

    private void _Button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_SaveActionPerformed
        // TODO add your handling code here:
        updateControlsPanel();
    }//GEN-LAST:event__Button_SaveActionPerformed

    
    public void updateControlsPanel(){
        
        maxRacks = Integer.parseInt(_FormattedTF_MaxRacks.getText());
        if(maxRacks > 20){
            maxRacks = 20;
        }        
        maxFans = Integer.parseInt(_FormattedTF_MaxFans.getText());
        if(maxFans > 100){
            maxFans = 100;
        }
        maxSG = Integer.parseInt(_FormattedTF_MaxSG.getText());
        if(maxSG > 20){
            maxSG = 20;
        }
        maxComp = Integer.parseInt(_FormattedTF_MaxComp.getText());
        if(maxComp > 100){
            maxComp = 100;
        }
        maxSystems = Integer.parseInt(_FormattedTF_MaxSystems.getText());
        if(maxSystems > 100){
            maxSystems = 100;
        }
        
        cp.updateSliderSettings(maxRacks, maxFans, maxSG, maxComp, maxSystems);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _Button_Defaults;
    private javax.swing.JButton _Button_Save;
    private javax.swing.JFormattedTextField _FormattedTF_MaxComp;
    private javax.swing.JFormattedTextField _FormattedTF_MaxFans;
    private javax.swing.JFormattedTextField _FormattedTF_MaxRacks;
    private javax.swing.JFormattedTextField _FormattedTF_MaxSG;
    private javax.swing.JFormattedTextField _FormattedTF_MaxSystems;
    private javax.swing.JLabel _Label_Log;
    private javax.swing.JLabel _Label_MaxComp;
    private javax.swing.JLabel _Label_MaxFans;
    private javax.swing.JLabel _Label_MaxRacks;
    private javax.swing.JLabel _Label_MaxSG;
    private javax.swing.JLabel _Label_MaxSystems;
    private javax.swing.JLabel _Label_RackSettings;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
