package Creator;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.SwingUtilities;

/**
 * The display frame which shows the different backgrounds
 *
 * @author EricGummerson
 */
public class DisplayFrame extends javax.swing.JFrame {

    public BackgroundMain bg; // main panel 
    // Loads panel
    public MainFrame mf;
    public ArrayList<BackgroundRack> rackTabs;
    public BackgroundLoad bgl;
    public BackgroundFinancial bgf;
    public BackgroundEnergy bge;
    public BackgroundGlycol bgg;
    public ControlSettings cs;
    public DisplaySettings ds;
    private boolean stopUpdate;

    /**
     * Creates new form DisplayFrame
     *
     * @param mf
     * @param css
     * @param dss
     */
    public DisplayFrame(MainFrame mf, ControlSettings css, DisplaySettings dss) {
        initComponents();
        this.stopUpdate = true;
        this.mf = mf;
        this.cs = css;
        this.ds = dss;
        rackTabs = new ArrayList<>();
        bg = new BackgroundMain(this);
        _TabbedPane_Tabs.add("Main", bg);
        for (int i = 1; i <= this.cs.getNumRacks(); i++) {
            BackgroundRack br = new BackgroundRack(this, (i - 1));
            _TabbedPane_Tabs.add("Rack " + i, br);
            rackTabs.add(br);
        }

        bgl = new BackgroundLoad(this);
        bgf = new BackgroundFinancial(this);
        bge = new BackgroundEnergy(this);
        bgg = new BackgroundGlycol(this);
        _TabbedPane_Tabs.add("Loads", bgl);
        _TabbedPane_Tabs.add("Financial", bgf);
        _TabbedPane_Tabs.add("Energy", bge);
        _TabbedPane_Tabs.add("Glycol", bgg);

        this.stopUpdate = false;
    }

    public void updateSettings(DisplaySettings dss) {
        
        //System.out.println("Size update ds " + ds.getDisplayWidth() + ", " + ds.getDisplayHeight());
        this.ds = dss;        
        //System.out.println("Size update dss " + dss.getDisplayWidth() + ", " + dss.getDisplayHeight());
        
        this.stopUpdate = true;
        this.setNewSize(ds.getDisplayWidth(), ds.getDisplayHeight());
        
        bg.updateDisplaySettings(ds);
        
        for (int i = 0; i < cs.getNumRacks(); i++) {
            if (rackTabs.get(i) != null) {
                rackTabs.get(i).updateDisplaySettings(ds);                
            }
        }
        bgl.updateDisplaySettings(ds);       
        bgf.updateDisplaySettings(ds);         
        bge.updateDisplaySettings(ds);         
        bgg.updateDisplaySettings(ds);         
        
        this.stopUpdate = false;
    }

    public boolean isStopUpdate() {
        return stopUpdate;
    }

    public void setStopUpdate(boolean stopUpdate) {
        this.stopUpdate = stopUpdate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _TabbedPane_Tabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customized Backgrounds");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(940, 0));
        setMinimumSize(new java.awt.Dimension(1200, 900));

        _TabbedPane_Tabs.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                _TabbedPane_TabsComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_TabbedPane_Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_TabbedPane_Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * resize the display
     *
     * @param evt
     */
    private void _TabbedPane_TabsComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event__TabbedPane_TabsComponentResized
        // TODO add your handling code her
        if (mf != null && !stopUpdate) {

            
            mf.updateDisplaySettingsSize(this.getSize());
            this.setPreferredSize(this.getSize());
            if (bg != null) {
                int w = bg.getWidth();
                int h = bg.getHeight();
                this.setTitle("Customized Backgrounds " + w + "x" + h);
                updateDisplays(cs, ds);
            }

        }
    }//GEN-LAST:event__TabbedPane_TabsComponentResized

    public void canClick(int panelIndex, boolean b) {
        int nt = _TabbedPane_Tabs.getTabCount();
        if (panelIndex == 0) {
            bg.setCanClick(b);
        } else if (panelIndex == (nt - 4)) {
            bgl.setCanClick(b);
        } else if (panelIndex == (nt - 3)) {
            bgf.setCanClick(b);        
        } else if (panelIndex == (nt - 2)) {
            bge.setCanClick(b);        
        } else if (panelIndex == (nt - 1)) {
            bgg.setCanClick(b);
        } else {
            panelIndex--;
            rackTabs.get(panelIndex).setCanClick(b);
        }
    }

    public void returnClick(Point point) {
        mf.returnClick(point);
    }

    public void setTab(int tab) {
        if (_TabbedPane_Tabs.getTabCount() > tab) {
            _TabbedPane_Tabs.setSelectedIndex(tab);
        }
    }

    public Map<String, Map<String, Rectangle>> getWidgetPositions() {

        this.pack();
        Map<String, Map<String, Rectangle>> masterMap = new LinkedHashMap<>();

        masterMap.put("Main", bg.positions());
        for (BackgroundRack b : rackTabs) {
            if (masterMap.containsKey("Rack")) {
                masterMap.get("R: " + b.rack.getName()).putAll(b.positions());
            } else {
                masterMap.put("R: " + b.rack.getName(), b.positions());
            }
        }

        masterMap.put("Loads", bgl.positions());
        masterMap.put("Financial", bgf.positions());
        masterMap.put("Energy", bge.positions());
        masterMap.put("Glycol", bgg.positions());

        return masterMap;
    }

    /**
     * Updates the form with the right information
     *
     * @param css
     * @param dss
     */
    public void updateDisplays(ControlSettings css, DisplaySettings dss) {
        this.cs = css;
        this.ds = dss;

        if (!stopUpdate) {
            DisplayFrame t = this;
            SwingUtilities.invokeLater(new Runnable() {

                @Override
                public void run() {

                    try {
                        int selected = _TabbedPane_Tabs.getSelectedIndex();
                        int nt = _TabbedPane_Tabs.getTabCount();
                        // update the main
                        bg.updateRacks(cs.getRacks(), cs.getNumRacks(), ds.getFont(), ds.getBorder(),
                                cs.getImgStr(), cs.getStoreName());

                        for (int i = nt - 5; i > cs.getNumRacks(); i--) {
                            _TabbedPane_Tabs.remove(i);
                        }

                        for (int i = 0; i < cs.getNumRacks(); i++) {
                            if (rackTabs.size() > i) {
                                if (rackTabs.get(i) != null) {
                                    rackTabs.get(i).updateRacks(cs.getRackIndex(i), cs.getNumRacks(), ds.getFont(), ds.getBorder(), cs.getImgStr(), cs.getStoreName(), cs.getRackNames());
                                    _TabbedPane_Tabs.add(rackTabs.get(i), i + 1);
                                    _TabbedPane_Tabs.setTitleAt(i + 1, cs.getRackNames()[i]);
                                }
                            } else {
                                rackTabs.add(new BackgroundRack(t, i));
                                rackTabs.get(i).updateRacks(cs.getRackIndex(i), cs.getNumRacks(), ds.getFont(), ds.getBorder(), cs.getImgStr(), cs.getStoreName(), cs.getRackNames());
                                _TabbedPane_Tabs.add(rackTabs.get(i), i + 1);
                                _TabbedPane_Tabs.setTitleAt(i + 1, cs.getRackNames()[i]);
                            }
                        }

                        bgl.updateRacks(cs.getRacks(), cs.getNumRacks(), ds.getFont(), ds.getBorder(), cs.getImgStr(), cs.getStoreName());
                        bgf.updateRacks(cs.getRacks(), cs.getNumRacks(), ds.getFont(), ds.getBorder(), cs.getImgStr(), cs.getStoreName());
                        bge.updateRacks(cs.getRacks(), cs.getNumRacks(), ds.getFont(), ds.getBorder(), cs.getImgStr(), cs.getStoreName());
                        bgg.updateRacks(cs.getRacks(), cs.getNumRacks(), ds.getFont(), ds.getBorder(), cs.getImgStr(), cs.getStoreName());
                        if (selected == (nt - 4)) {
                            if (_TabbedPane_Tabs.getTabCount() < nt) {
                                selected--; // loads tab selected
                            } else {
                                selected = _TabbedPane_Tabs.getTabCount() - 1;
                            }
                        } else if (selected < (_TabbedPane_Tabs.getTabCount() - 1)) {
                            // good                    
                        } else if (selected >= (_TabbedPane_Tabs.getTabCount() - 1)) {
                            selected--;
                        }
                        _TabbedPane_Tabs.setSelectedIndex(selected);
                        t.pack();
                        int w = bg.getWidth();
                        int h = bg.getHeight();
                        t.setTitle("Customized Backgrounds " + w + "x" + h);

                    } catch (NullPointerException e) {
                        System.out.println("Probably that tree map null pointer exception");
                    }
                }

            });
        }

    }

    /**
     * update the logo
     */
    public void updateLogo() {

        bg.updateImageURL("");
        for (int i = 0; i < cs.getNumRacks(); i++) {
            if (rackTabs.get(i) != null) {
                rackTabs.get(i).updateImageURL("");
            }
        }
        bgl.updateImageURL("");
        bgf.updateImageURL("");
        bge.updateImageURL("");
        bgg.updateImageURL("");
    }

    /**
     * update the logo
     *
     * @param img String file path
     */
    public void updateLogo(String img) {
        bg.updateImageURL(img);
        for (int i = 0; i < cs.getNumRacks(); i++) {
            if (rackTabs.get(i) != null) {
                rackTabs.get(i).updateImageURL(img);
            }
        }
        bgl.updateImageURL(img);
        bgf.updateImageURL(img);
        bge.updateImageURL(img);
        bgg.updateImageURL(img);
    }

    /**
     * sets the size of the display frame
     *
     * @param width the width of the frame
     * @param height the height of the frame
     */
    public void setNewSize(int width, int height) {        
        this.setSize(width, height);
        this.setPreferredSize(new Dimension(width, height));

    }

    /**
     * gets the selected panel on the tabbed pane
     *
     * @return component
     */
    public Component getCurrentPane() {
        return _TabbedPane_Tabs.getSelectedComponent();
    }

    public Component[] getPanelPictures() {
        Component[] c = new Component[cs.getNumRacks() + 3];

        c[0] = bg;

        for (int i = 1; i <= cs.getNumRacks(); i++) {
            c[i] = rackTabs.get(i - 1);
        }

        c[c.length - 4] = bgl;
        c[c.length - 3] = bgf;
        c[c.length - 2] = bge;
        c[c.length - 1] = bgg;

        return c;

    }

    /**
     * Gets the number of tabs being displayed
     *
     * @return number of tabs
     */
    public int getTabCount() {
        return _TabbedPane_Tabs.getTabCount();
    }

    /**
     * Changes the selected index of the tabbed pane
     *
     * @param index int index to switch to 0 - (tab count - 1)
     */
    public void changeTab(int index) {
        _TabbedPane_Tabs.setSelectedIndex(index);
    }

    /**
     * Gets the current tab selection of the tabbed pane
     *
     * @return int index of the selected index
     */
    public int getTabSelection() {
        return _TabbedPane_Tabs.getSelectedIndex();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane _TabbedPane_Tabs;
    // End of variables declaration//GEN-END:variables
}
