/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Creator;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.TreeMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author EricGummerson
 */
public class GenericVariablesFrame extends javax.swing.JFrame {

    private TaskManagerPanel parent;
    private Map<String, Integer> gv;
    private Map<String, List> mappings;
    private Map<String, String> gv_links;     // (String, List) - Generic variable name, list of unformatted strings to link
    private DefaultListModel gvList;
    private DefaultListModel unformattedList;
    private DefaultListModel toAddList;
    private DefaultListModel gvLinksList;

    /**
     * Creates new form GenericVariablesFrame
     */
    public GenericVariablesFrame(Map<String, Integer> gv, Map<String, List> mappings, Map<String, String> gv_links, TaskManagerPanel parent) {

        this.gv = gv;
        this.mappings = mappings;
        this.parent = parent;
        this.gv_links = gv_links;

        gvList = new DefaultListModel();
        unformattedList = new DefaultListModel();
        toAddList = new DefaultListModel();
        gvLinksList = new DefaultListModel();

        initComponents();
        loadLists();
        loadGV_LinkList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        _List_GV = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        _List_UnformattedStrings = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        _List_StringsToAdd = new javax.swing.JList();
        _Button_Add = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        _List_GV_Links = new javax.swing.JList();
        _Button_Import = new javax.swing.JButton();
        _Button_Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _List_GV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _List_GV.setModel(gvList);
        _List_GV.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(_List_GV);

        _List_UnformattedStrings.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _List_UnformattedStrings.setModel(unformattedList);
        _List_UnformattedStrings.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        _List_UnformattedStrings.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                _List_UnformattedStringsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(_List_UnformattedStrings);

        _List_StringsToAdd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _List_StringsToAdd.setModel(toAddList);
        _List_StringsToAdd.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(_List_StringsToAdd);

        _Button_Add.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _Button_Add.setText("Add");
        _Button_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_AddActionPerformed(evt);
            }
        });

        _List_GV_Links.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _List_GV_Links.setModel(gvLinksList);
        _List_GV_Links.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(_List_GV_Links);

        _Button_Import.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _Button_Import.setText("Import");
        _Button_Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_ImportActionPerformed(evt);
            }
        });

        _Button_Delete.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _Button_Delete.setText("Delete");
        _Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Button_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_Button_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(_Button_Import, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_Button_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(_Button_Import, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_Button_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Button_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _List_UnformattedStringsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event__List_UnformattedStringsValueChanged
        if (!evt.getValueIsAdjusting()) {
            if (!_List_UnformattedStrings.isSelectionEmpty()) {
                loadFormattedString(_List_UnformattedStrings.getSelectedValue().toString());
            }
        }
    }//GEN-LAST:event__List_UnformattedStringsValueChanged

    private void _Button_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_AddActionPerformed
        // TODO add your handling code here:
        if (!_List_GV.isSelectionEmpty() && !_List_UnformattedStrings.isSelectionEmpty()) {
            String gvName = _List_GV.getSelectedValue().toString();
            String unformattedName = _List_UnformattedStrings.getSelectedValue().toString();
            
            gv_links.put(gvName,unformattedName);

            _List_GV.clearSelection();
            _List_UnformattedStrings.clearSelection();

            loadGV_LinkList();

        }


    }//GEN-LAST:event__Button_AddActionPerformed

    private void _Button_ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_ImportActionPerformed
        // TODO add your handling code here:
        this.parent.insertGV(gv_links);
        this.dispose();
    }//GEN-LAST:event__Button_ImportActionPerformed

    private void _Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Button_DeleteActionPerformed
        // TODO add your handling code here:
        if (!_List_GV_Links.isSelectionEmpty()) {

            int[] selectedIndices = _List_GV_Links.getSelectedIndices();
            
            for (int i = selectedIndices.length - 1; i >= 0; i--) {
                String [] parts = gvLinksList.get(i).toString().split(" -> ");
                System.out.println("Removed: " + gv_links.remove(parts[0]));
                gvLinksList.removeElementAt(selectedIndices[i]);
            }
        }
    }//GEN-LAST:event__Button_DeleteActionPerformed

    private void loadLists() {

        gvList.clear();
        for (String k : gv.keySet()) {
            gvList.addElement(k);
        }

        unformattedList.clear();
        for (String k : mappings.keySet()) {
            unformattedList.addElement(k);
        }
    }

    private void loadGV_LinkList() {
        gvLinksList.clear();
        for (Entry<String, String> entry : gv_links.entrySet()) {        
            gvLinksList.addElement(entry.getKey() + " -> " + entry.getValue());            
        }
    }

    private void loadFormattedString(String item) {

        toAddList.clear();
        for (Object s : mappings.get(item)) {
            toAddList.addElement(s);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _Button_Add;
    private javax.swing.JButton _Button_Delete;
    private javax.swing.JButton _Button_Import;
    private javax.swing.JList _List_GV;
    private javax.swing.JList _List_GV_Links;
    private javax.swing.JList _List_StringsToAdd;
    private javax.swing.JList _List_UnformattedStrings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
